<?php

function grouprelation_menu() {
  $items['group/search'] = array(
    'page callback' => 'grouprelation_search',
    'access arguments' => array(
      'access content',
    ),
    'type' => MENU_CALLBACK,
  );
  $items['group/name/%'] = array(
    'page callback' => 'groupinfo_show',
    'access arguments' => array(
      'access content',
    ),
    'page arguments' => array(
      2,
    ),
    'type' => MENU_CALLBACK,
  );
  $items['group/fine_record/%'] = array(
    'page callback' => 'query_fine_record',
    'access arguments' => array(
      'access content',
    ),
    'page arguments' => array(
      2,
    ),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function find_group_json($group_name){
    $year=2016;
    $json_base_path = base_path().'companydata/group_relation/';
    $json_filename=$group_name.'_'.$year.'_list.json';
    $json_file = $json_base_path .$group_name.'/'.$json_filename;
    #$json_test = $json_base_path .$json_filename;

    echo "<script>var json_path = '".$json_file."';</script>";
}

function init_library(){
    $module_base_path = drupal_get_path('module', 'grouprelation');
    $plugin_base_path = $module_base_path."/plugin";
    $options = array(
        'scope' => 'footer',
        'type' => 'file',
    );
    
    drupal_add_css($plugin_base_path."/bootstrap/css/bootstrap.min.css", $options);
    drupal_add_js($plugin_base_path."/jQuery/jQuery-2.2.0.min.js", $options);
    drupal_add_js($plugin_base_path."/datatables/jquery.dataTables.min.js", $options);
    drupal_add_js($plugin_base_path."/datatables/dataTables.buttons.min.js", $options);
    drupal_add_js($plugin_base_path."/datatables/dataTables.bootstrap.min.js", $options);
    drupal_add_js($plugin_base_path."/d3/d3.v3.min.js", $options);
}

function init_custom(){
    $module_base_path = drupal_get_path('module', 'grouprelation');
    $js_base_path = $module_base_path."/js/";
    $options = array(
        'scope' => 'footer',
        'type' => 'file',
    );
    drupal_add_js($js_base_path."/init.js", $options);
    drupal_add_js($js_base_path."/group.js", $options);
    drupal_add_js($js_base_path."/graph.js", $options);
}

function groupinfo_show($group_name){
    //drupal_set_message(var_export($group_name, TRUE));
    init_library();
    init_custom();
  
    find_group_json($group_name);
    $output='';
    /*
    $output .= '<div id="table_summery_area" style="display: none">';
    $output .= '<table id="table_summery">';
    $output .= '<thead><tr>';
    $output .= '<th >集團名稱</th>';
    $output .= '<th >集團公司總數</th>';
    $output .= '<th >是否有裁罰記錄</th>';
    $output .= '<th >有裁罰記錄公司總數</th>';
    $output .= '<th >裁罰記錄總數</th>';
    $output .= '<th >裁罰金額總數</th>';
    $output .= '<th >關係圖</th>';
    $output .= '</tr></thead></table>';
    $output .= '</div>';
    */

    $output .= '<div id="table_summery_area" style="display: none; width:100%">';
    $output .= '<div id="summery_content">';
    $output .= '</div></div>';

    $output .= '<div id="table_company_area" style="display: none" >';
    $output .= '<table id="table_company" >';
    $output .= '<thead><tr>';
    $output .= '<th >子公司統一編號</th>';
    $output .= '<th >子公司名稱</th>';
    $output .= '<th >母公司列表</th>';
    $output .= '</tr></thead></table>';
    $output .= '</div>';

    $output .= '<div id="table_fine_company_area" style="display: none" >';
    $output .= '<table id="table_fine_company">';
    $output .= '<thead><tr>';
    $output .= '<th >公司名稱</th>';
    $output .= '<th >統一編號</th>';
    $output .= '<th >裁罰記錄總數</th>';
    $output .= '<th >裁罰金額總數</th>';
    $output .= '</tr></thead></table>';
    $output .= '</div>';

    $output .= '<div id="table_fine_record_area" style="display: none" >';
    $output .= '<table id="table_fine_record">';
    $output .= '<thead><tr>';
    $output .= '<th >工廠名稱</th>';
    $output .= '<th >裁罰日期</th>';
    $output .= '<th >裁罰金額</th>';
    $output .= '<th >違反法律</th>';
    $output .= '<th >是否請願</th>';
    $output .= '</tr></thead></table>';
    $output .= '</div>';

    return $output;
}

function query_belong_group($search_target, $search_type){
  $year=2016;
  $query = "SELECT factory_group.group from factory_group";
  if($search_type=='source'){
    $query .= " where sublist_source like :search_target";
    $args = array(
        ':search_target' => '%'.db_like($search_target).'%',
        ':year'=>$year
    );
  }
  else if($search_type=='taxcode'){
    $query .= " where taxcode_source =:search_target";
    $args = array(
        ':search_target' => $search_target,
        ':year'=>$year
    );
  }
   else if($search_type=='stock'){
    $query .= " where stock =:search_target";
    $args = array(
        ':search_target' => $search_target,
        ':year'=>$year
    );
  }
  $query .= " and year=:year";
  $result = db_query($query, $args);
  $rows = array();
  foreach($result as $r) {
    array_push($rows, $r->group);
  }
  //drupal_set_message(var_export($year, TRUE));

  echo "<script>var group_name =".json_encode($rows).";</script>";
}

function grouprelation_search(){
    $title = '集團搜尋';
    drupal_set_title($title);

    if ($_REQUEST['search_stock']!=''){
       $target=$_REQUEST['search_stock'];
       query_belong_group($target, 'stock');
    }  
    else if($_REQUEST['search_text']!=''){
      $target=$_REQUEST['search_text'];
      $new_target=str_replace("臺灣", "台灣", $target);
      query_belong_group($new_target, 'source');
    }
    else if ($_REQUEST['search_taxcode']!=''){
       $target=$_REQUEST['search_taxcode'];
       query_belong_group($new_target, 'taxcode');
    }  
    else{
      //drupal_set_message(var_export('all', TRUE));
      echo "<script>var group_name = 'all';</script>";
    }

    init_library();
    init_custom();

    $output = '';
    $output .= '<form>';
    $output .= '<div><span>集團名稱或是公司名稱: </span><input id="search_text" name="search_text" type="text" /></div>';
    $output .= '<div><span>公司股票: </span><input id="search_stock" name="search_stock" type="text" /></div>';
    $output .= '<div><span>公司統一編號: </span><input id="search_taxcode" name="search_taxcode" type="text" /></div>';
    $output .= '<div><button type="submit">查詢</button></div>';
    $output .= '</form>';

    $output .= '<div id="table_group_list_area" style="display: none">';
    $output .= '<table id="table_group_list">';
    $output .= '</table>';
    $output .= '</div>';

    $output .= '<div><span id="search_warning" style="display: none">沒有符合的結果</span></div>';
    return $output;
}

function query_fine_record($taxcode){
    //if($_REQUEST['taxcode']!=''){
    //  $taxcode=$_REQUEST['taxcode'];

    $query = "SELECT factory_fine.facility_name, factory_fine.penalty_date, factory_fine.penalty_money, factory_fine.transgress_law, factory_fine.is_petition, factory_fine.petition_results, factory_corp.registration_no from factory_fine, factory_corp where factory_corp.corp_id=:taxcode and factory_corp.registration_no=factory_fine.registration_no";
    $args = array(
      ':taxcode' => $taxcode,
    );
    $result = db_query($query, $args);
    $rows = array();
    foreach($result as $r) {
      $row = array(
        'facility_name'=>$r->facility_name,
        'penalty_date'=>$r->penalty_date,
        'penalty_money'=>$r->penalty_money,
        'transgress_law'=>$r->transgress_law,
        'is_petition'=>$r->is_petition,
        'petition_results'=>$r->petition_results
      );
      array_push($rows, $row);
    }
    echo json_encode($rows);
    //}
}

function grouprelation_index() {
  // set title
  $title = '集團搜尋';
  drupal_set_title($title);

  // prepare static file path
  $json_base_path = base_path().'/companydata/';
  $json_file_a = $path . 'test.json';

  // add js file to footer
  $module_base_path = drupal_get_path('module', 'grouprelation');
  $js_base_path = $module_base_path."/js/";
  $plugin_base_path = $muldie_base_path."/plugin/";

  $options = array(
    'scope' => 'footer',
    'type' => 'file',
  );
  drupal_add_js("$js_base_path/test.js", $options);

  // database query
  $query = "SELECT * FROM {factory_group} WHERE id = :id";
  $args = array(
    ':id' => 1,
  );
  $result = db_query($query, $args);
  $rows = array();
  foreach($result as $r) {
    $row = array(
      $r->id,
      $r->year,
      $r->group,
    );
    $rows[] = implode(',', $row);
  }

  // begin output
  $output = '';
  $output .= 'abc';
  $output .= '<a href="#">link</a>';
  $output .= '<div>'.implode('<br>', $rows).'</div>';

  // return to show output
  return $output;
}   